### ISSUE TITLE
Update registration time in Java

### ISSUE THREAD

**Issue by domcermak** [BelinaJaroslav/DBS_2020#15]
#8

# API
> change_vaccination_time (registered-vaccination-id) (vaccination-date) (vaccination-time)

# Todo
- create new option in `src/app/options` called `ChangeVaccinationTime` inherited from `Option` class
- implement necessary logic
- use parsers from https://github.com/BelinaJaroslav/DBS_2020/blob/master/src/app/options/RegisterPatient.java, you can move them to Option class and declare them as protected
- have a look at other update options such as https://github.com/BelinaJaroslav/DBS_2020/blob/master/src/app/options/SetVaccinationCompleted.java
- update help instructions

# Validations
- registration_id exist
- time is in correct format

**Comment by navratil-matej** [comment]
Note that "time is in correct format" is verified by the provided time parser.

**Comment by domcermak** [comment]
Yup, that's intentional.
